export interface MaintenanceCategory {
  id: string;
  name: string;
  items: string[];
}

export const MAINTENANCE_CATEGORIES: MaintenanceCategory[] = [
  {
    id: "motor_internos",
    name: "1. Motor y componentes internos",
    items: [
      "Bloque del motor",
      "Culata",
      "Junta de culata",
      "Pistones",
      "Anillos de pistón",
      "Bielas",
      "Cigüeñal",
      "Cojinetes",
      "Árbol de levas",
      "Válvulas de admisión",
      "Válvulas de escape",
      "Resortes de válvulas",
      "Balancines",
      "Taqués hidráulicos",
      "Cadena, correa o engranajes de distribución",
      "Tensor de distribución",
      "Poleas",
      "Volante motor",
      "Soportes de motor",
      "Cárter de aceite",
      "Tapa de válvulas",
      "Empaques y retenes",
      "Motor de arranque",
      "Alternador",
    ],
  },
  {
    id: "admision_aire",
    name: "2. Sistema de admisión de aire",
    items: [
      "Filtro de aire",
      "Caja del filtro de aire",
      "Conductos de admisión",
      "Mangueras de admisión",
      "Cuerpo de aceleración",
      "Múltiple de admisión",
      "Sensor MAF",
      "Sensor MAP",
      "Sensor de temperatura de aire",
      "Válvula IAC o control de ralentí",
      "Turbo",
      "Intercooler",
      "Wastegate",
      "Válvula de descarga o blow-off",
      "Compresor volumétrico",
    ],
  },
  {
    id: "sistema_combustible",
    name: "3. Sistema de combustible",
    items: [
      "Tanque de combustible",
      "Tapa del tanque",
      "Boca de llenado",
      "Bomba de combustible",
      "Aforador o sensor de nivel",
      "Filtro de combustible",
      "Líneas o mangueras de combustible",
      "Riel de inyección",
      "Inyectores",
      "Regulador de presión",
      "Bomba de alta presión",
      "Carburador",
      "Válvula de purga EVAP",
      "Canister de carbón activado",
      "Sensor de presión de combustible",
    ],
  },
  {
    id: "sistema_encendido",
    name: "4. Sistema de encendido",
    items: [
      "Batería",
      "Bobinas de encendido",
      "Bujías",
      "Cables de bujías",
      "Distribuidor",
      "Módulo de encendido",
      "Sensor de posición del cigüeñal",
      "Sensor de posición del árbol de levas",
      "Interruptor de encendido",
      "Llave o sistema de encendido sin llave",
    ],
  },
  {
    id: "sistema_lubricacion",
    name: "5. Sistema de lubricación",
    items: [
      "Aceite de motor",
      "Bomba de aceite",
      "Filtro de aceite",
      "Colador de aceite",
      "Varilla medidora de aceite",
      "Tapón de drenaje",
      "Enfriador de aceite",
      "Sensor de presión de aceite",
      "Sensor de nivel de aceite",
      "Conductos internos de lubricación",
    ],
  },
  {
    id: "sistema_refrigeracion",
    name: "6. Sistema de refrigeración",
    items: [
      "Radiador",
      "Refrigerante o líquido anticongelante",
      "Bomba de agua",
      "Termostato",
      "Electroventilador",
      "Ventilador mecánico",
      "Mangueras de radiador",
      "Depósito de expansión",
      "Tapa del radiador",
      "Sensor de temperatura del refrigerante",
      "Radiador de calefacción",
      "Enfriador de transmisión",
    ],
  },
  {
    id: "escape_emisiones",
    name: "7. Sistema de escape y emisiones",
    items: [
      "Múltiple de escape",
      "Empaque del múltiple",
      "Tubo de escape",
      "Catalizador",
      "Sensor de oxígeno o sonda lambda",
      "Resonador",
      "Silenciador",
      "Cola de escape",
      "Filtro de partículas diésel (DPF)",
      "Válvula EGR",
      "Enfriador EGR",
      "Sistema SCR / AdBlue",
      "Sensor NOx",
      "Sensores de temperatura de escape",
    ],
  },
  {
    id: "transmision",
    name: "8. Caja de cambios y transmisión",
    items: [
      "Caja de cambios manual",
      "Caja automática",
      "Transmisión CVT",
      "Transmisión de doble embrague",
      "Convertidor de torque",
      "Embrague",
      "Disco de embrague",
      "Prensa de embrague",
      "Collarín o balinera de embrague",
      "Cilindro maestro de embrague",
      "Cilindro esclavo de embrague",
      "Palanca de cambios",
      "Cables o varillaje de cambios",
      "Aceite de transmisión",
      "Módulo de control de transmisión",
      "Sensor de posición de cambios",
      "Soportes de transmisión",
    ],
  },
  {
    id: "traccion_ejes",
    name: "9. Tracción, ejes y diferencial",
    items: [
      "Diferencial delantero",
      "Diferencial trasero",
      "Diferencial central",
      "Caja de transferencia",
      "Cardán o eje de transmisión",
      "Semiejes",
      "Juntas homocinéticas",
      "Guardapolvos de homocinética",
      "Eje trasero",
      "Cubos de rueda",
      "Bloqueo de diferencial",
      "Sistema 4x4 o AWD",
    ],
  },
  {
    id: "suspension",
    name: "10. Suspensión",
    items: [
      "Amortiguadores",
      "Resortes o espirales",
      "Ballestas",
      "Barras de torsión",
      "Struts o conjuntos MacPherson",
      "Copelas de amortiguador",
      "Brazos de suspensión",
      "Tijeras",
      "Bujes de suspensión",
      "Rótulas",
      "Barra estabilizadora",
      "Bujes de barra estabilizadora",
      "Bieletas",
      "Manguetas",
      "Subchasis",
      "Eje rígido",
      "Suspensión neumática",
      "Compresor de suspensión neumática",
      "Bolsas de aire de suspensión",
      "Sensores de altura",
    ],
  },
  {
    id: "direccion",
    name: "11. Dirección",
    items: [
      "Volante",
      "Columna de dirección",
      "Cremallera de dirección",
      "Caja de dirección",
      "Bomba hidráulica de dirección",
      "Depósito de líquido hidráulico",
      "Mangueras hidráulicas",
      "Motor eléctrico de dirección asistida",
      "Terminales de dirección",
      "Barras axiales",
      "Rótulas de dirección",
      "Sensor de ángulo de dirección",
      "Bloqueo de dirección",
    ],
  },
  {
    id: "frenos",
    name: "12. Sistema de frenos",
    items: [
      "Pedal de freno",
      "Servofreno o booster",
      "Bomba principal de freno",
      "Depósito de líquido de frenos",
      "Líquido de frenos",
      "Líneas rígidas de freno",
      "Mangueras de freno",
      "Mordazas o cálipers",
      "Pastillas de freno",
      "Discos de freno",
      "Tambores de freno",
      "Zapatas de freno",
      "Cilindros de rueda",
      "Freno de mano",
      "Cable de freno de mano",
      "Freno de estacionamiento eléctrico",
      "Módulo ABS",
      "Sensores ABS",
      "Anillos reluctores",
      "Control de estabilidad ESP/ESC",
      "Control de tracción",
    ],
  },
  {
    id: "ruedas",
    name: "13. Ruedas y neumáticos",
    items: [
      "Rines",
      "Llantas o neumáticos",
      "Llanta de repuesto",
      "Tuercas o pernos de rueda",
      "Tapacubos",
      "Válvulas de aire",
      "Sensores TPMS",
      "Centro de rin",
      "Kit de reparación de neumáticos",
      "Gato hidráulico o mecánico",
      "Llave de ruedas",
    ],
  },
  {
    id: "electrico",
    name: "14. Sistema eléctrico y electrónico",
    items: [
      "Bornes de batería",
      "Fusibles",
      "Relés",
      "Caja de fusibles",
      "Cableado eléctrico",
      "Arnés principal",
      "Módulos electrónicos",
      "ECU o computadora del motor",
      "BCM o módulo de carrocería",
      "Módulo de airbags",
      "Módulo de transmisión",
      "Sensores",
      "Actuadores",
      "Conector OBD-II",
      "Sistema CAN Bus",
      "Tierra o masa eléctrica",
      "Inmovilizador",
      "Alarma",
    ],
  },
  {
    id: "iluminacion",
    name: "15. Iluminación y señalización",
    items: [
      "Faros delanteros",
      "Luces bajas",
      "Luces altas",
      "Luces diurnas DRL",
      "Luces de posición",
      "Direccionales o señales",
      "Luces de emergencia",
      "Luces traseras",
      "Luces de freno",
      "Tercera luz de freno",
      "Luz de reversa",
      "Luz de placa",
      "Luces antiniebla",
      "Luces interiores",
      "Luces de cortesía",
      "Luz de guantera",
      "Bombillos LED, halógenos o xenón",
      "Módulo de faros",
      "Interruptor de luces",
      "Palanca de direccionales",
    ],
  },
  {
    id: "carroceria",
    name: "16. Carrocería y estructura exterior",
    items: [
      "Capó",
      "Parachoques delantero",
      "Parachoques trasero",
      "Parrilla frontal",
      "Guardabarros",
      "Puertas",
      "Bisagras de puertas",
      "Manijas exteriores",
      "Cerraduras",
      "Techo",
      "Techo corredizo",
      "Techo panorámico",
      "Maletero o baúl",
      "Compuerta trasera",
      "Spoiler",
      "Estribos",
      "Molduras",
      "Emblemas",
      "Placa",
      "Chasis",
      "Largueros",
      "Traviesas",
      "Panel frontal",
      "Panel trasero",
      "Refuerzos estructurales",
    ],
  },
  {
    id: "vidrios_espejos",
    name: "17. Vidrios, espejos y limpiaparabrisas",
    items: [
      "Parabrisas",
      "Vidrio trasero",
      "Vidrios laterales",
      "Vidrios de puertas",
      "Vidrios fijos",
      "Elevavidrios eléctricos",
      "Motor de elevavidrios",
      "Interruptores de vidrios",
      "Espejos laterales",
      "Espejo retrovisor interior",
      "Motor de ajuste de espejos",
      "Espejos calefactados",
      "Limpiaparabrisas",
      "Brazos de limpiaparabrisas",
      "Plumillas",
      "Motor de limpiaparabrisas",
      "Depósito de líquido limpiaparabrisas",
      "Bomba de agua limpiaparabrisas",
      "Boquillas rociadoras",
      "Sensor de lluvia",
    ],
  },
  {
    id: "interior",
    name: "18. Interior, cabina y confort",
    items: [
      "Asientos delanteros",
      "Asientos traseros",
      "Cabeceras",
      "Rieles de asientos",
      "Cinturones de seguridad",
      "Hebillas de cinturón",
      "Tablero de instrumentos",
      "Cuadro de instrumentos",
      "Tacómetro",
      "Velocímetro",
      "Indicador de combustible",
      "Pantalla multimedia",
      "Radio",
      "Parlantes",
      "Amplificador",
      "Micrófono manos libres",
      "Puertos USB",
      "Cargador inalámbrico",
      "Guantera",
      "Consola central",
      "Portavasos",
      "Parasoles",
      "Manijas interiores",
      "Tapicería",
      "Alfombras",
      "Techo interior",
      "Pedales",
      "Botones y mandos",
    ],
  },
  {
    id: "aire_acondicionado",
    name: "19. Aire acondicionado, calefacción y ventilación",
    items: [
      "Compresor de aire acondicionado",
      "Condensador",
      "Evaporador",
      "Filtro de cabina",
      "Válvula de expansión",
      "Gas refrigerante",
      "Mangueras de A/C",
      "Presostato",
      "Ventilador interno o blower",
      "Motor del blower",
      "Ductos de ventilación",
      "Rejillas de aire",
      "Panel de control de clima",
      "Actuadores de compuertas",
      "Calefacción",
      "Desempañador delantero",
      "Desempañador trasero",
    ],
  },
  {
    id: "seguridad",
    name: "20. Seguridad pasiva y activa",
    items: [
      "Airbag del conductor",
      "Airbag del pasajero",
      "Airbags laterales",
      "Airbags de cortina",
      "Pretensores de cinturón",
      "Sensores de impacto",
      "Reposacabezas activos",
      "Cámara de reversa",
      "Cámara 360°",
      "Sensores de parqueo",
      "Radar delantero",
      "Radar trasero",
      "Sensor de punto ciego",
      "Sensor de proximidad",
      "Alerta de colisión",
      "Frenado autónomo de emergencia",
      "Asistente de mantenimiento de carril",
      "Control crucero adaptativo",
      "Sistema de monitoreo del conductor",
    ],
  },
  {
    id: "acceso",
    name: "21. Sistemas de acceso y cierre",
    items: [
      "Llave física",
      "Llave inteligente",
      "Control remoto",
      "Botón de encendido",
      "Cerradura de puerta",
      "Actuador de cierre centralizado",
      "Módulo de cierre centralizado",
      "Sensor de proximidad de llave",
      "Apertura remota de baúl",
      "Apertura eléctrica de compuerta trasera",
    ],
  },
  {
    id: "conectividad",
    name: "22. Sistema de información y conectividad",
    items: [
      "Pantalla central",
      "Sistema multimedia",
      "GPS o navegador",
      "Antena de radio",
      "Antena GPS",
      "Antena de telefonía",
      "Bluetooth",
      "Wi-Fi",
      "Apple CarPlay",
      "Android Auto",
      "Cámara de tablero",
      "Puerto OBD-II",
      "Telemetría",
      "Sistema de rastreo GPS",
      "Módulo de conectividad",
    ],
  },
  {
    id: "hibridos_electricos",
    name: "23. Vehículos híbridos y eléctricos",
    items: [
      "Motor eléctrico",
      "Batería de alto voltaje",
      "Batería auxiliar de 12 V",
      "Inversor",
      "Convertidor DC-DC",
      "Cargador a bordo",
      "Puerto de carga",
      "Cable de carga",
      "Sistema de gestión de batería BMS",
      "Controlador del motor eléctrico",
      "Reductora",
      "Sistema de recuperación de energía",
      "Refrigeración de batería",
      "Contactor de alto voltaje",
      "Fusibles de alto voltaje",
      "Cableado naranja de alto voltaje",
    ],
  },
  {
    id: "accesorios",
    name: "24. Elementos de emergencia y accesorios",
    items: [
      "Triángulos de seguridad",
      "Chaleco reflectivo",
      "Botiquín",
      "Extintor",
      "Kit de carretera",
      "Cables pasa corriente",
      "Compresor portátil",
      "Linterna",
      "Barras portaequipaje",
      "Portabicicletas",
      "Enganche o remolque",
      "Cámara dashcam",
      "Tapetes",
      "Cobertor de carro",
    ],
  },
  {
    id: "otros",
    name: "25. Otros",
    items: ["Mantenimiento General", "Revisión Preventiva", "Lavado / Detailing", "Otro"],
  },
];

export const getCategoryByItem = (item: string): string | null => {
  for (const cat of MAINTENANCE_CATEGORIES) {
    if (cat.items.includes(item)) {
      return cat.id;
    }
  }
  return null;
};
