export interface MaintenanceCategory {
  id: string;
  name: string;
  items: string[];
}

export const MAINTENANCE_CATEGORIES: MaintenanceCategory[] = [
  {
    id: "motor_internos",
    name: "1. Motor y componentes internos",
    items: [
      "Bloque del motor",
      "Culata",
      "Junta de culata",
      "Pistones",
      "Anillos de pistón",
      "Bielas",
      "Cigüeñal",
      "Cojinetes",
      "Árbol de levas",
      "Válvulas de admisión",
      "Válvulas de escape",
      "Resortes de válvulas",
      "Balancines",
      "Taqués hidráulicos",
      "Cadena, correa o engranajes de distribución",
      "Tensor de distribución",
      "Poleas",
      "Volante motor",
      "Soportes de motor",
      "Cárter de aceite",
      "Tapa de válvulas",
      "Empaques y retenes",
      "Motor de arranque",
      "Alternador",
    ],
  },
  {
    id: "admision_aire",
    name: "2. Sistema de admisión de aire",
    items: [
      "Filtro de aire",
      "Caja del filtro de aire",
      "Conductos de admisión",
      "Mangueras de admisión",
      "Cuerpo de aceleración",
      "Múltiple de admisión",
      "Sensor MAF",
      "Sensor MAP",
      "Sensor de temperatura de aire",
      "Válvula IAC o control de ralentí",
      "Turbo",
      "Intercooler",
      "Wastegate",
      "Válvula de descarga o blow-off",
      "Compresor volumétrico",
    ],
  },
  {
    id: "sistema_combustible",
    name: "3. Sistema de combustible",
    items: [
      "Tanque de combustible",
      "Tapa del tanque",
      "Boca de llenado",
      "Bomba de combustible",
      "Aforador o sensor de nivel",
      "Filtro de combustible",
      "Líneas o mangueras de combustible",
      "Riel de inyección",
      "Inyectores",
      "Regulador de presión",
      "Bomba de alta presión",
      "Carburador",
      "Válvula de purga EVAP",
      "Canister de carbón activado",
      "Sensor de presión de combustible",
    ],
  },
  {
    id: "sistema_encendido",
    name: "4. Sistema de encendido",
    items: [
      "Batería",
      "Bobinas de encendido",
      "Bujías",
      "Cables de bujías",
      "Distribuidor",
      "Módulo de encendido",
      "Sensor de posición del cigüeñal",
      "Sensor de posición del árbol de levas",
      "Interruptor de encendido",
      "Llave o sistema de encendido sin llave",
    ],
  },
  {
    id: "sistema_lubricacion",
    name: "5. Sistema de lubricación",
    items: [
      "Aceite de motor",
      "Bomba de aceite",
      "Filtro de aceite",
      "Colador de aceite",
      "Varilla medidora de aceite",
      "Tapón de drenaje",
      "Enfriador de aceite",
      "Sensor de presión de aceite",
      "Sensor de nivel de aceite",
      "Conductos internos de lubricación",
    ],
  },
  {
    id: "sistema_refrigeracion",
    name: "6. Sistema de refrigeración",
    items: [
      "Radiador",
      "Refrigerante o líquido anticongelante",
      "Bomba de agua",
      "Termostato",
      "Electroventilador",
      "Ventilador mecánico",
      "Mangueras de radiador",
      "Depósito de expansión",
      "Tapa del radiador",
      "Sensor de temperatura del refrigerante",
      "Radiador de calefacción",
      "Enfriador de transmisión",
    ],
  },
  {
    id: "escape_emisiones",
    name: "7. Sistema de escape y emisiones",
    items: [
      "Múltiple de escape",
      "Empaque del múltiple",
      "Tubo de escape",
      "Catalizador",
      "Sensor de oxígeno o sonda lambda",
      "Resonador",
      "Silenciador",
      "Cola de escape",
      "Filtro de partículas diésel (DPF)",
      "Válvula EGR",
      "Enfriador EGR",
      "Sistema SCR / AdBlue",
      "Sensor NOx",
      "Sensores de temperatura de escape",
    ],
  },
  {
    id: "transmision",
    name: "8. Caja de cambios y transmisión",
    items: [
      "Caja de cambios manual",
      "Caja automática",
      "Transmisión CVT",
      "Transmisión de doble embrague",
      "Convertidor de torque",
      "Embrague",
      "Disco de embrague",
      "Prensa de embrague",
      "Collarín o balinera de embrague",
      "Cilindro maestro de embrague",
      "Cilindro esclavo de embrague",
      "Palanca de cambios",
      "Cables o varillaje de cambios",
      "Aceite de transmisión",
      "Módulo de control de transmisión",
      "Sensor de posición de cambios",
      "Soportes de transmisión",
    ],
  },
  {
    id: "traccion_ejes",
    name: "9. Tracción, ejes y diferencial",
    items: [
      "Diferencial delantero",
      "Diferencial trasero",
      "Diferencial central",
      "Caja de transferencia",
      "Cardán o eje de transmisión",
      "Semiejes",
      "Juntas homocinéticas",
      "Guardapolvos de homocinética",
      "Eje trasero",
      "Cubos de rueda",
      "Bloqueo de diferencial",
      "Sistema 4x4 o AWD",
    ],
  },
  {
    id: "suspension",
    name: "10. Suspensión",
    items: [
      "Amortiguadores",
      "Resortes o espirales",
      "Ballestas",
      "Barras de torsión",
      "Struts o conjuntos MacPherson",
      "Copelas de amortiguador",
      "Brazos de suspensión",
      "Tijeras",
      "Bujes de suspensión",
      "Rótulas",
      "Barra estabilizadora",
      "Bujes de barra estabilizadora",
      "Bieletas",
      "Manguetas",
      "Subchasis",
      "Eje rígido",
      "Suspensión neumática",
      "Compresor de suspensión neumática",
      "Bolsas de aire de suspensión",
      "Sensores de altura",
    ],
  },
  {
    id: "direccion",
    name: "11. Dirección",
    items: [
      "Volante",
      "Columna de dirección",
      "Cremallera de dirección",
      "Caja de dirección",
      "Bomba hidráulica de dirección",
      "Depósito de líquido hidráulico",
      "Mangueras hidráulicas",
      "Motor eléctrico de dirección asistida",
      "Terminales de dirección",
      "Barras axiales",
      "Rótulas de dirección",
      "Sensor de ángulo de dirección",
      "Bloqueo de dirección",
    ],
  },
  {
    id: "frenos",
    name: "12. Sistema de frenos",
    items: [
      "Pedal de freno",
      "Servofreno o booster",
      "Bomba principal de freno",
      "Depósito de líquido de frenos",
      "Líquido de frenos",
      "Líneas rígidas de freno",
      "Mangueras de freno",
      "Mordazas o cálipers",
      "Pastillas de freno",
      "Discos de freno",
      "Tambores de freno",
      "Zapatas de freno",
      "Cilindros de rueda",
      "Freno de mano",
      "Cable de freno de mano",
      "Freno de estacionamiento eléctrico",
      "Módulo ABS",
      "Sensores ABS",
      "Anillos reluctores",
      "Control de estabilidad ESP/ESC",
      "Control de tracción",
    ],
  },
  {
    id: "ruedas",
    name: "13. Ruedas y neumáticos",
    items: [
      "Rines",
      "Llantas o neumáticos",
      "Llanta de repuesto",
      "Tuercas o pernos de rueda",
      "Tapacubos",
      "Válvulas de aire",
      "Sensores TPMS",
      "Centro de rin",
      "Kit de reparación de neumáticos",
      "Gato hidráulico o mecánico",
      "Llave de ruedas",
    ],
  },
  {
    id: "electrico",
    name: "14. Sistema eléctrico y electrónico",
    items: [
      "Bornes de batería",
      "Fusibles",
      "Relés",
      "Caja de fusibles",
      "Cableado eléctrico",
      "Arnés principal",
      "Módulos electrónicos",
      "ECU o computadora del motor",
      "BCM o módulo de carrocería",
      "Módulo de airbags",
      "Módulo de transmisión",
      "Sensores",
      "Actuadores",
      "Conector OBD-II",
      "Sistema CAN Bus",
      "Tierra o masa eléctrica",
      "Inmovilizador",
      "Alarma",
    ],
  },
  {
    id: "iluminacion",
    name: "15. Iluminación y señalización",
    items: [
      "Faros delanteros",
      "Luces bajas",
      "Luces altas",
      "Luces diurnas DRL",
      "Luces de posición",
      "Direccionales o señales",
      "Luces de emergencia",
      "Luces traseras",
      "Luces de freno",
      "Tercera luz de freno",
      "Luz de reversa",
      "Luz de placa",
      "Luces antiniebla",
      "Luces interiores",
      "Luces de cortesía",
      "Luz de guantera",
      "Bombillos LED, halógenos o xenón",
      "Módulo de faros",
      "Interruptor de luces",
      "Palanca de direccionales",
    ],
  },
  {
    id: "carroceria",
    name: "16. Carrocería y estructura exterior",
    items: [
      "Capó",
      "Parachoques delantero",
      "Parachoques trasero",
      "Parrilla frontal",
      "Guardabarros",
      "Puertas",
      "Bisagras de puertas",
      "Manijas exteriores",
      "Cerraduras",
      "Techo",
      "Techo corredizo",
      "Techo panorámico",
      "Maletero o baúl",
      "Compuerta trasera",
      "Spoiler",
      "Estribos",
      "Molduras",
      "Emblemas",
      "Placa",
      "Chasis",
      "Largueros",
      "Traviesas",
      "Panel frontal",
      "Panel trasero",
      "Refuerzos estructurales",
    ],
  },
  {
    id: "vidrios_espejos",
    name: "17. Vidrios, espejos y limpiaparabrisas",
    items: [
      "Parabrisas",
      "Vidrio trasero",
      "Vidrios laterales",
      "Vidrios de puertas",
      "Vidrios fijos",
      "Elevavidrios eléctricos",
      "Motor de elevavidrios",
      "Interruptores de vidrios",
      "Espejos laterales",
      "Espejo retrovisor interior",
      "Motor de ajuste de espejos",
      "Espejos calefactados",
      "Limpiaparabrisas",
      "Brazos de limpiaparabrisas",
      "Plumillas",
      "Motor de limpiaparabrisas",
      "Depósito de líquido limpiaparabrisas",
      "Bomba de agua limpiaparabrisas",
      "Boquillas rociadoras",
      "Sensor de lluvia",
    ],
  },
  {
    id: "interior",
    name: "18. Interior, cabina y confort",
    items: [
      "Asientos delanteros",
      "Asientos traseros",
      "Cabeceras",
      "Rieles de asientos",
      "Cinturones de seguridad",
      "Hebillas de cinturón",
      "Tablero de instrumentos",
      "Cuadro de instrumentos",
      "Tacómetro",
      "Velocímetro",
      "Indicador de combustible",
      "Pantalla multimedia",
      "Radio",
      "Parlantes",
      "Amplificador",
      "Micrófono manos libres",
      "Puertos USB",
      "Cargador inalámbrico",
      "Guantera",
      "Consola central",
      "Portavasos",
      "Parasoles",
      "Manijas interiores",
      "Tapicería",
      "Alfombras",
      "Techo interior",
      "Pedales",
      "Botones y mandos",
    ],
  },
  {
    id: "aire_acondicionado",
    name: "19. Aire acondicionado, calefacción y ventilación",
    items: [
      "Compresor de aire acondicionado",
      "Condensador",
      "Evaporador",
      "Filtro de cabina",
      "Válvula de expansión",
      "Gas refrigerante",
      "Mangueras de A/C",
      "Presostato",
      "Ventilador interno o blower",
      "Motor del blower",
      "Ductos de ventilación",
      "Rejillas de aire",
      "Panel de control de clima",
      "Actuadores de compuertas",
      "Calefacción",
      "Desempañador delantero",
      "Desempañador trasero",
    ],
  },
  {
    id: "seguridad",
    name: "20. Seguridad pasiva y activa",
    items: [
      "Airbag del conductor",
      "Airbag del pasajero",
      "Airbags laterales",
      "Airbags de cortina",
      "Pretensores de cinturón",
      "Sensores de impacto",
      "Reposacabezas activos",
      "Cámara de reversa",
      "Cámara 360°",
      "Sensores de parqueo",
      "Radar delantero",
      "Radar trasero",
      "Sensor de punto ciego",
      "Sensor de proximidad",
      "Alerta de colisión",
      "Frenado autónomo de emergencia",
      "Asistente de mantenimiento de carril",
      "Control crucero adaptativo",
      "Sistema de monitoreo del conductor",
    ],
  },
  {
    id: "acceso",
    name: "21. Sistemas de acceso y cierre",
    items: [
      "Llave física",
      "Llave inteligente",
      "Control remoto",
      "Botón de encendido",
      "Cerradura de puerta",
      "Actuador de cierre centralizado",
      "Módulo de cierre centralizado",
      "Sensor de proximidad de llave",
      "Apertura remota de baúl",
      "Apertura eléctrica de compuerta trasera",
    ],
  },
  {
    id: "conectividad",
    name: "22. Sistema de información y conectividad",
    items: [
      "Pantalla central",
      "Sistema multimedia",
      "GPS o navegador",
      "Antena de radio",
      "Antena GPS",
      "Antena de telefonía",
      "Bluetooth",
      "Wi-Fi",
      "Apple CarPlay",
      "Android Auto",
      "Cámara de tablero",
      "Puerto OBD-II",
      "Telemetría",
      "Sistema de rastreo GPS",
      "Módulo de conectividad",
    ],
  },
  {
    id: "hibridos_electricos",
    name: "23. Vehículos híbridos y eléctricos",
    items: [
      "Motor eléctrico",
      "Batería de alto voltaje",
      "Batería auxiliar de 12 V",
      "Inversor",
      "Convertidor DC-DC",
      "Cargador a bordo",
      "Puerto de carga",
      "Cable de carga",
      "Sistema de gestión de batería BMS",
      "Controlador del motor eléctrico",
      "Reductora",
      "Sistema de recuperación de energía",
      "Refrigeración de batería",
      "Contactor de alto voltaje",
      "Fusibles de alto voltaje",
      "Cableado naranja de alto voltaje",
    ],
  },
  {
    id: "accesorios",
    name: "24. Elementos de emergencia y accesorios",
    items: [
      "Triángulos de seguridad",
      "Chaleco reflectivo",
      "Botiquín",
      "Extintor",
      "Kit de carretera",
      "Cables pasa corriente",
      "Compresor portátil",
      "Linterna",
      "Barras portaequipaje",
      "Portabicicletas",
      "Enganche o remolque",
      "Cámara dashcam",
      "Tapetes",
      "Cobertor de carro",
    ],
  },
  {
    id: "otros",
    name: "25. Otros",
    items: ["Mantenimiento General", "Revisión Preventiva", "Lavado / Detailing", "Otro"],
  },
];

export const MOTO_MAINTENANCE_CATEGORIES: MaintenanceCategory[] = [
  {
    id: "moto_motor",
    name: "1. Motor",
    items: [
      "Bloque del motor",
      "Culata",
      "Junta de culata",
      "Pistón",
      "Anillos de pistón",
      "Biela",
      "Cigüeñal",
      "Árbol de levas",
      "Válvulas de admisión",
      "Válvulas de escape",
      "Resortes de válvulas",
      "Balancines",
      "Cadena de distribución",
      "Tensor de distribución",
      "Guías de cadena",
      "Tapa de válvulas",
      "Cárter",
      "Empaques",
      "Retenes",
      "Soportes del motor",
      "Volante magnético",
      "Magneto"
    ]
  },
  {
    id: "moto_lubricacion",
    name: "2. Sistema de lubricación",
    items: [
      "Aceite del motor",
      "Filtro de aceite",
      "Colador de aceite",
      "Bomba de aceite",
      "Radiador de aceite",
      "Sensor de presión de aceite",
      "Tapón de drenaje",
      "Varilla medidora",
      "Mirilla de aceite"
    ]
  },
  {
    id: "moto_refrigeracion",
    name: "3. Sistema de refrigeración",
    items: [
      "Radiador",
      "Bomba de agua",
      "Termostato",
      "Electroventilador",
      "Mangueras",
      "Depósito de expansión",
      "Refrigerante",
      "Sensor de temperatura",
      "Tapa del radiador"
    ]
  },
  {
    id: "moto_combustible",
    name: "4. Sistema de combustible",
    items: [
      "Tanque",
      "Tapa del tanque",
      "Llave de gasolina",
      "Bomba de combustible",
      "Filtro de gasolina",
      "Mangueras",
      "Inyectores",
      "Cuerpo de aceleración",
      "Carburador",
      "Chicler principal",
      "Chicler de baja",
      "Flotador",
      "Aguja del carburador",
      "Sensor de nivel",
      "Sensor de presión",
      "Regulador de presión"
    ]
  },
  {
    id: "moto_admision",
    name: "5. Sistema de admisión",
    items: [
      "Filtro de aire",
      "Caja del filtro",
      "Conductos de admisión",
      "Múltiple de admisión",
      "Sensor MAP",
      "Sensor MAF",
      "Sensor IAT",
      "Cuerpo de aceleración",
      "Válvula ISC"
    ]
  },
  {
    id: "moto_encendido",
    name: "6. Sistema de encendido",
    items: [
      "Batería",
      "Bobina de encendido",
      "Bujía",
      "Capuchón de bujía",
      "CDI",
      "ECU",
      "Estator",
      "Regulador/rectificador",
      "Sensor CKP",
      "Interruptor de encendido",
      "Interruptor de paro"
    ]
  },
  {
    id: "moto_escape",
    name: "7. Sistema de escape",
    items: [
      "Múltiple",
      "Empaque del escape",
      "Tubo de escape",
      "Silenciador",
      "Catalizador",
      "Protector térmico",
      "Sensor de oxígeno",
      "Válvula de escape"
    ]
  },
  {
    id: "moto_caja_embrague",
    name: "8. Caja de cambios y embrague",
    items: [
      "Caja de cambios",
      "Selector de cambios",
      "Horquilla selectora",
      "Tambor selector",
      "Engranajes",
      "Eje primario",
      "Eje secundario",
      "Embrague",
      "Discos de embrague",
      "Discos separadores",
      "Campana de embrague",
      "Prensa de embrague",
      "Cable de embrague",
      "Cilindro maestro hidráulico",
      "Cilindro esclavo"
    ]
  },
  {
    id: "moto_transmision",
    name: "9. Transmisión final",
    items: [
      "Cadena",
      "Piñón delantero",
      "Catalina",
      "Tensor de cadena",
      "Guía de cadena",
      "Protector de cadena",
      "Correa",
      "Polea delantera",
      "Polea trasera",
      "Cardán",
      "Eje cardán",
      "Crucetas",
      "Caja del cardán"
    ]
  },
  {
    id: "moto_suspension_delantera",
    name: "10. Suspensión delantera",
    items: [
      "Barras telescópicas",
      "Horquilla invertida",
      "Tubos internos",
      "Barras externas",
      "Retenes",
      "Guardapolvos",
      "Aceite de suspensión",
      "Tapas superiores",
      "Resortes",
      "Casquillos"
    ]
  },
  {
    id: "moto_suspension_trasera",
    name: "11. Suspensión trasera",
    items: [
      "Amortiguador",
      "Monoamortiguador",
      "Doble amortiguador",
      "Resorte",
      "Bieletas",
      "Basculante",
      "Bujes del basculante",
      "Eje del basculante",
      "Rodamientos"
    ]
  },
  {
    id: "moto_direccion",
    name: "12. Dirección",
    items: [
      "Manillar",
      "Puños",
      "Contrapesos",
      "Tija superior",
      "Tija inferior",
      "Rodamientos de dirección",
      "Columna de dirección",
      "Topes de dirección"
    ]
  },
  {
    id: "moto_frenos",
    name: "13. Sistema de frenos",
    items: [
      "Disco delantero",
      "Disco trasero",
      "Pastillas delanteras",
      "Pastillas traseras",
      "Mordaza delantera",
      "Mordaza trasera",
      "Bomba de freno delantera",
      "Bomba de freno trasera",
      "Depósito de líquido",
      "Líquido de frenos",
      "Latiguillos",
      "Pedal de freno",
      "Manigueta de freno",
      "Sensor ABS",
      "Módulo ABS",
      "Tambor",
      "Zapatas"
    ]
  },
  {
    id: "moto_ruedas",
    name: "14. Ruedas y neumáticos",
    items: [
      "Llanta delantera",
      "Llanta trasera",
      "Rin delantero",
      "Rin trasero",
      "Radios",
      "Nipples",
      "Cubo delantero",
      "Cubo trasero",
      "Rodamientos",
      "Retenes",
      "Válvulas",
      "Sensor TPMS"
    ]
  },
  {
    id: "moto_electrico",
    name: "15. Sistema eléctrico",
    items: [
      "Batería",
      "Fusibles",
      "Relés",
      "Arnés eléctrico",
      "ECU",
      "CDI",
      "Regulador",
      "Estator",
      "Alternador",
      "Cableado",
      "Tierra eléctrica",
      "Interruptores",
      "Conectores"
    ]
  },
  {
    id: "moto_iluminacion",
    name: "16. Iluminación",
    items: [
      "Faro delantero",
      "Bombillo LED",
      "Bombillo halógeno",
      "Luz alta",
      "Luz baja",
      "Luz trasera",
      "Luz de freno",
      "Direccionales delanteras",
      "Direccionales traseras",
      "Luz de placa",
      "DRL",
      "Interruptor de luces"
    ]
  },
  {
    id: "moto_instrumentacion",
    name: "17. Instrumentación",
    items: [
      "Velocímetro",
      "Tacómetro",
      "Pantalla TFT",
      "Pantalla LCD",
      "Indicador de combustible",
      "Indicador de temperatura",
      "Indicador de marcha",
      "Indicador ABS",
      "Indicador FI",
      "Indicador de batería",
      "Sensor de velocidad"
    ]
  },
  {
    id: "moto_controles",
    name: "18. Controles",
    items: [
      "Manigueta de embrague",
      "Manigueta de freno",
      "Acelerador",
      "Cable del acelerador",
      "Interruptor de arranque",
      "Interruptor de luces",
      "Interruptor de direccionales",
      "Bocina",
      "Interruptor de paro",
      "Pedal de cambios",
      "Pedal de freno",
      "Pedales del conductor",
      "Pedales del pasajero"
    ]
  },
  {
    id: "moto_chasis",
    name: "19. Chasis y carrocería",
    items: [
      "Chasis",
      "Subchasis",
      "Tanque",
      "Tapas laterales",
      "Guardabarros delantero",
      "Guardabarros trasero",
      "Colín",
      "Asiento",
      "Asiento del pasajero",
      "Parrilla",
      "Quilla",
      "Protector de motor",
      "Defensas",
      "Sliders",
      "Cubrecadena"
    ]
  },
  {
    id: "moto_seguridad",
    name: "20. Sistema de seguridad",
    items: [
      "Cerradura de dirección",
      "Llave",
      "Llave inteligente",
      "Inmovilizador",
      "Alarma",
      "Rastreador GPS",
      "ABS",
      "Control de tracción",
      "Quickshifter",
      "Modos de conducción",
      "Control crucero"
    ]
  },
  {
    id: "moto_accesorios",
    name: "21. Accesorios",
    items: [
      "Maletas laterales",
      "Top Case",
      "Bolsa de tanque",
      "Soporte para celular",
      "Puerto USB",
      "Toma de 12V",
      "Cámara deportiva",
      "Defensas",
      "Cubrepuños",
      "Parabrisas",
      "Protector de radiador",
      "Protector de cárter",
      "Cubremanos",
      "Soporte GPS",
      "Caballete central",
      "Caballete lateral"
    ]
  },
  {
    id: "moto_electrica",
    name: "22. Motocicletas eléctricas",
    items: [
      "Motor eléctrico",
      "Batería de tracción",
      "Controlador",
      "Inversor",
      "Convertidor DC-DC",
      "Puerto de carga",
      "Cargador",
      "Cable de carga",
      "BMS",
      "Sensores de batería",
      "Fusibles de alto voltaje"
    ]
  },
  {
    id: "moto_general",
    name: "23. Mantenimiento general",
    items: [
      "Cambio de aceite",
      "Cambio de filtro de aceite",
      "Cambio de filtro de aire",
      "Cambio de filtro de combustible",
      "Cambio de refrigerante",
      "Cambio de líquido de frenos",
      "Cambio de aceite de suspensión",
      "Ajuste de válvulas",
      "Sincronización",
      "Limpieza de inyectores",
      "Limpieza de carburador",
      "Cambio de bujía",
      "Cambio de kit de arrastre",
      "Lubricación de cadena",
      "Tensado de cadena",
      "Alineación de ruedas",
      "Balanceo de ruedas",
      "Cambio de llantas",
      "Revisión eléctrica",
      "Diagnóstico electrónico",
      "Cambio de batería",
      "Revisión general",
      "Lavado técnico",
      "Pulido",
      "Detallado",
      "Inspección pre-viaje",
      "Inspección técnico-mecánica"
    ]
  }
];

export const getCategoryByItem = (item: string, vehicleType: 'car' | 'moto' = 'car'): string | null => {
  const categories = vehicleType === 'moto' ? MOTO_MAINTENANCE_CATEGORIES : MAINTENANCE_CATEGORIES;
  for (const cat of categories) {
    if (cat.items.includes(item)) {
      return cat.id;
    }
  }
  return null;
};
